
$quote "

$
$ Translation into the German language on 94/08/12 by:
$ Deutsche Uebersetzung am 12.08.94 von:
$
$ NET Network Expert Team GmbH
$ Figarostr. 3
$ D-70597 Stuttgart
$ Tel. +49 711 9768921
$ Fax. +49 711 9768933
$

$
$ Welcome message...
$

$ --- some problems here with \n
$ 1 "Willkommen in der wunderbaren Welt des Gopher!\n\n"
$ 2 "Gopher hat bestimmte Nutzungseinschränkungen und keinerlei\n"
$ 3 "Garantie. Sehen Sie bitte in der Datei 'Copyright' nach, die \n"
$ 4 "in der Distribution enthalten ist.\n\n"
$ 5 "Copyright 1991-2000 by the Regents of the University of Minnesota\n\n"
$ 6 "Internet Gopher Information Client %s.%s patch%d (%s)\n"
$ 7 "Zum fortfahren Eingabetaste drücken\n"

$ 
$ Errors in .gopherrc
$
8 "Kann Gopher-Konfigurationsdatei nicht schreiben!!"

$
$ Help for command line 
$

$ --- some problems here with \n
$ 9 "Aufruf: %s [-sSbDr] [-T typ] [-p pfad] [-t titel] [hostname port]+\n"
$ 10 "     -s      Sicherer Modus, Benutzer ohne eigenen Zugang\n"
$ 11 "     -S      Sicherer Modus, Benutzer mit eigenem Zugang\n"
$ 12 "     -p pfad Pfadangabe zum Anfangsartikel\n"
$ 13 "     -T typ  Typ des Anfangsartikels\n"
$ 14 "     -i      Suchargument (fuer -T 7)\n"
$ 15 "     -b      Lesezeichen zuerst\n"
$ 16 "     -r      Entfernter Benutzer\n"
$ 17 "     -D      Debug-Modus\n"

$
$ Pager help..
$

18 "Betrachter-Hilfe"
19 "u, ^G, Pfeil-links     : Zurück zur Auswahl"
20 "Leertaste, Pfeil-unten : Zur nächsten Seite"
21 "b, Pfeil-oben          : Zur vorherigen Seite"
22 "/                      : Textsuche"
23 "m                      : Dokument versenden"
24 "s                      : Dokument speichern"
25 "p                      : Dokument drucken"
26 "D                      : Dokument herunterladen"

$ 
$ New Application Menu
$ 

27 "Name Inhaltstyp"
28 "Anzeigeanwendung"
29 "Druckanwendung"

$ 
$ Top Level Options
$ 

30 "Allgemeine Optionen"
31 "Anzeigeanwendungen konfigurieren"
32 "Druckanwendungen konfigurieren"
33 "Neuen Inhaltstyp definieren"

$
$ Telnet connection
$

34 "Warnung!!!!!, Sie sind dabei, das Internet Gopher Programm"
35 "zu verlassen und sich an einen anderen Host anzuschließen."
36 "Sollten Sie hängenbleiben, drücken Sie Control und"
37 "die ]-Taste, danach geben Sie quit ein"
38 "die ^-Taste, dann tippen Sie q."
39 "Verbindung nach %.40s, Port %d mittels %s."
40 "Verbindung nach %.40s mittels %s."
41 "Verwenden Sie den Zugang \"%.40s\" zum anmelden"

$
$ HTML menu
$

42 "Warnung!!!!!, Sie sind dabei, das Internet Gopher Programm"
43 "zu verlassen und einen HTML-Betrachter aufzurufen.  Verwenden Sie"
44 "die Betrachter-Hilfe wenn Ihnen die Kommandos nicht geläufig sind."
45 "Nach Beenden des Betrachters kommen Sie in den Internet"
46 "Gopher Klienten zurück."

$
$ Other html msgs
$

47 "Bedaure, dieser Klient unterstützt kein HTML"

$
$ gopher.c
$

48 "Bedaure, kann keinen Administrator für diesen Artikel finden!"

$ 
$ Gripe form msgs
$ 

49 "Drüecken Sie die Eingabetaste um Ihre Nachricht zu versenden."
50 "Drüecken Sie die Tabulator-Taste am Ende jeder Eingabezeile."
51 "Thema"
52 "Problem"
53 "Kann keine Post versenden..."
54 "Sende Beschwerde an %s..."
55 "Worte nach denen gesucht werden soll"
56 "  Seite: %d/%d"
57 " Hilfe, "
58 " Beenden"
59 " vorherige Auswahl"
$ --- some problems here with \n
$ 60 "%s: Nichts für das Hauptmenü empfangen, kann nicht weitermachen\n"
61 "%sm%s zum versenden, %sD%s zum herunterladen, %ss%s zum speichern, oder %sp%s zum drucken:"
62 ", %sm%s zum versenden, %sD%s zum herunterladen:"
63 ", <m> zum versenden, <D> zum herunterladen:"
$ --- some problems here with \n
$ 64 ",\n   <m> zum versenden, <D> zum herunterladen, <s> zum speichern, oder <p> zum drucken:"
65 "Adressen-Syntax abgelehnt..."
66 "Fett Suchworte im Betrachter"
67 "Lesezeichen"
68 "Kann alte Datei nicht öffnen.."
69 "Kann nicht auf SYS$SCRATCH schreiben!"
70 "Kann nicht ins /tmp Verzeichnis schreiben!"
71 "Kann gewünschte Datei nicht öffnen.."
72 "Keine Verbindung zu Rechner %.40s, port %d."
73 "Wählen Sie einen Dokumenttyp"
74 "Methode zum herunterladen"
75 "An einen neuen Gopher Server binden"
76 "Via Gopher an einen anonymen FTP Server binden"
77 "Verbindungsaufbau..."
78 "Verbindung fehlgeschlagen: %s."
79 "Verbindung zu anderem Rechner fehlgeschlagen."
80 "Konnte '%s' nicht erstellen"
$ --- some problems here with \n
$ 81 "Konnte %s nicht ausführen\n"
82 "Konnte Text nicht finden"
$ --- some problems here with \n
$ 83 "Konnte keine Temporärdatei erstellen!\n"
84 "Druckerproblem entdeckt, bedaure..."
85 "Fehler beim TPU-Aufruf (Betrachter)!!!"
86 "Ende: u"
87 "Hole Felder..."
88 "Datei nicht erfolgreich transferiert"
89 "Gopher Verzeichnis-Information"
90 "Gopher Fehler"
91 "Gopher Datei"
92 "Gopher Hilfedatei"
93 "Gopher Artikelinformation"
94 "Gopher Optionen"
95 "Gopher Übertragungsfehler"
96 "Hilfe: ?"
97 "Lokaler Gopherserver: %.59s"
98 "Zu befragender Rechner:"
99 "Rechnername"
100 "Rechnername ist unbekannt."
$ --- some problems here with \n
$ 101 "Ich kenne Ihren Terminaltyp nicht\n"
102 "Internet Gopher Informationsklient v%s.%s.%d"
103 "Link Info"
104 "Lokales Datum und Uhrzeit"
105 "Versende aktuelles Dokument an:"
106 "Versende Datei..."
107 "Versende Datei an %s..."
108 "Filmbetrachtung noch nicht implementiert"
109 "Name dieses Lesezeichens:"
110 "Netzwerkfehler"
111 "Nein"
112 "Keine Lesezeichen definiert"
113 "Kein Anzeigekommando mit dieser Ansicht verknüpft!"
114 "Kein solcher Anwender '%s'"
115 "Seite nach unten: <Leertaste>"
116 "Seite nach unten: Leertaste"
117 "Seite nach oben: b"
118 "Port"
119 "Tasten: "
120 "Zum fortfahren Eingabetaste drücken"
$ --- some problems here with \n
$ 121 "Wenn bereit, Eingabetaste drücken\n"
122 "Aktuelles Dokument drucken"
123 "Problem beim schreiben"
124 "Wirklich verlassen (y/n) ?"
125 "Empfange Verzeichnis..."
126 "Empfange Datei..."
127 "Empfange HTML-Seite..."
128 "Empfange Information..."
129 "Empfange MIME-Datei..."
130 "Empfange Film..."
131 "Empfange Ton..."
132 "Empfange Bild..."
133 "Hole Verzeichnis..."
134 "Zurück zur Auswahl: u"
135 "Hauptmenü: "
136 "Speichern als Datei:"
137 "Artikelliste speichern in Datei:"
138 "Speichere Datei..."
139 "Suche Verzeichnistitel für:"
140 "Suche fehlgeschlagen..."
141 "Text absuchen nach:"
142 "Durchsuche Text..."
143 "Suche..."
144 "Selektor (Optional)"
145 "Zeige lokales Datum und Zeit"
$ --- some problems here with \n
$ 146 "Umfang     Sprache       Dokumenttyp\n"
$ 147 "---------- ------------- ----------------------------\n"
148 "Bedaure, kann diese Datei nicht zeigen"
149 "Bedaure, kann Haupt-Verzeichnis nicht löschen."
150 "Bedaure, kann das nicht herunterladen!"
151 "Bedaure, kann aus Lesezeichen keine Lesezeichen machen"
152 "Bedaure, kann mit diesem Zugang keine Dateien speichern"
153 "Bedaure, kann mit diesem Zugang keine Subprozesse starten"
154 "Bedaure, kann den Artikel nicht als Datei speichern!"
155 "Bedaure, kann dieses Dokument nicht drucken"
156 "Bedaure, kein Druckverfahren für dieses Dokument"
157 "Bedaure, telnet ist nicht verfügbar."
158 "Bedaure, diese Maschine unterstüzt keine Bilder"
159 "Bedaure, diese Maschine unterstützt keinen Ton"
160 "Bedaure, tn3270 ist nicht verfügbar."
161 "Bedaure, Sie dürfen keine Dateien drucken"
162 "Bedaure, Sie düfen keine Dateien speichern"
163 "Bedaure, Sie dürfen im Sicherheits-Modus keine Optionen setzen."
164 "Bedaure, Sie dürfen das nicht"
165 "Bedaure, diese Machine unterstützt keine Filme"
166 "Bedaure, keine Anzeigeprogramm für die Datei...."
167 "Spawn nach DCL fehlgeschlagen!"
168 "Spawn zur voreingestellten Shell fehlgeschlagen!"
$ --- some problems here with \n
$ 169 "Starte DCL Subprozess. Rückkehr zum Gopher mit 'Logout'.\n"
$ 170 "Starte Ihre Standard-Shell.  Rückkehr zum Gopher mit 'Exit'.\n\n"
$ 171 "Starten Sie jetzt das einlesen...\n\n"
$ 172 "Starten Sie jetzt Ihr Transferprogramm...\n"
173 "Systemproblem, kann nicht versenden"
174 "Der Dateiname lautet:"
175 "Kann keine Socket allozieren."
176 "Unix piping erwünscht.  Überprüfen Sie Ihre Konfiguration!"
177 "Unbekannter Fehler."
178 "Verwenden Sie erst '/' um eine Suche zu definieren..."
179 "Ansehen Artikel Nr.: "
180 "Ja"
181 "Ihre Wahl"
$ --- some problems here with \n
$ 182 "\nHerunterladen abgschlossen. %d Bytes gesamt, %d Bytes/sek\n"
$ 183 "\nHerunterladen konnte nicht abgeschlossen werden, bedaure... \n"
$ 184 "\nZum fortfahren %sEingabetaste%s drücken"
$ 185 "\nZum fortfahren Eingabetaste drücken"
$ 186 "\n\nServer-Information\n"
187 "anonymous FTP Host"
$ --- some problems here with \n
$ 188 "Gopher: Keine Daten für Hauptmenü, kann nicht fortfahren\n"
189 "Das Lösch-Kommando 'd' gilt nur für Lesezeichen."
190 "^G           : Abbruch"
191 "OK: Eing."
192 "Tab, ^N      : Zum nächsten Feld"
193 "^P           : Zum vorherigen Feld"
194 "^F           : Nächste Seite zeigen"
195 "^B           : Vorherige Seite zeigen"
196 "^-           : Hilfe (^/ oder ^7 geht evtl. auch)"
197 "Eingabetaste : Formular übernehmen"
198 "[Hilfe: ^-]  [Abbruch: ^G]"
199 "  [Wert ändern: Leerzeichen]  [Liste: l]"
200 "Treffen Sie Ihre Auswahl"
$
$ Choose menu..
$

201 "Formular-Hilfe"
202 "^G            : Abbruch"
203 "Runter, ^N    : Nächster Auswahlpunkt"
204 "Hoch, ^P      : Vorheriger Auswahlpunkt"
205 "Leertaste, ^F : Nächste Seite"
206 "b, ^B         : Vorherige Seite"
207 "^             : Erste Seite"
208 "$             : Letzte Seite"
209 "0-9           : Bestimmter Auswahlpunkt"
210 "Eingabetaste  : Aktuellen Auswahlpunkt anwählen"
211 "Abbruch: ^G"
212 " (Standardwert)"
213 "Auswahldialog-Hilfe"
214 "Nichts verfügbar."
$ --- some problems here with \n
$ 215 "Achtung, fehlerhafte Zeile in gopherrc: %s\n"
216 "Breche abspeichern der Gopher-Konfiguration ab!!"
217 "Text"
218 "Eine neue Konfiguration ist verfügbar.  Laden?"
219 "Voreingestellter Systemdrucker"
220 "ANSI Drucker"
221 "Ausdruck nach"

$ Default language/region gopher+ view to choose

222 "De_DE"

$
$ A message that asks the User if they speak this language..
$
232 "Spraeken zie Deutcsh?"

$
$ Add to post-pager option list in SecureMode and NoShellMode
$
237 ", %sD%s zum herunterladen:"
238 ", <D> zum herunterladen:"

