
$quote "


$
$ Welcome message...
$

1 "Welcome to the wonderful world of Gopher!\n\n"
2 "Gopher has limitations on its use and comes without\n"
3 "a warranty.  Please refer to the file 'Copyright' included\n"
4 "in the distribution.\n\n"

5 "Copyright 1991-2000 by the Regents of the University of Minnesota\nCopyright (C) 2000-2002 John Goerzen and the gopher developers\n\n"
6 "Internet Gopher Information Client %s.%s patch%d (%s)\n"
7 "Press RETURN to continue\n"

$ 
$ Errors in .gopherrc
$
8 "Can't write gopher configuration file!!"

$
$ Help for command line 
$

9 "Usage: %s [-sSbDr] [-T type] [-p path] [-t title] [hostname port]+\n"
10 "     -s      secure mode, users without own account\n"
11 "     -S      secure mode, users with own account\n"
12 "     -p path specify path to initial item\n"
13 "     -T type Type of initial item\n"
14 "     -i      Search argument (for -T 7)\n"
15 "     -b      Bookmarks first\n"
16 "     -r      Remote user\n"
17 "     -D      Debug mode\n"

$
$ Pager help..
$

18 "Pager Help"
19 "u, ^G, left : Return to menu"
20 "space, down : Move to the next page"
21 "b, up       : Move to the previous page"
22 "/           : Search for text"
23 "m           : mail current document"
24 "s           : save current document"
25 "p           : print current document"
26 "D           : download current document"

$ 
$ New Application Menu
$ 
27 "Content-Type Name"
28 "Display Application"
29 "Printing Application"

$ 
$ Top Level Options
$ 
30 "General Options"
31 "Configure Display Applications"
32 "Configure Printing Applications"
33 "Define New Content-Type"

$
$ Telnet connection
$
34 "Warning!!!!!, you are about to leave the Internet"
35 "Gopher program and connect to another host. If"
36 "you get stuck press the control key and the"
37 "] key, and then type quit"
38 "^ key, and then type q."
39 "Connecting to %.40s, port %d using %s."
40 "Connecting to %.40s using %s."
41 "Use the account name \"%.40s\" to log in"
$
$ HTML menu
$
42 "Warning!!!!!, you are about to leave the Internet Gopher"
43 "Client and connect to an HTML Browser.  Use the Browser"
44 "Help if you are not familiar with its commands."
45 "Upon quitting from the Browser, you will be returned to"
46 "the Internet Gopher Client."
$
$ Other html msgs
$
47 "Sorry, this client does not support HTML"

$
$ gopher.c
$
48 "Can't find an administrator for this item, sorry!"

$ 
$ Gripe form msgs
$ 
49 "Hit the Enter key to send your message."
50 "Hit the Tab key at the end of each line you type."
51 "Subject"
52 "Problem"
53 "Cannot send mail..."
54 "Mailing gripe to %s..."
55 "Words to search for"
56 "  Page: %d/%d"
57 " for Help, "
58 " to Quit"
59 " to go up a menu"
60 "%s: Nothing received for main menu, can't continue\n"
61 "%sm%s to mail, %sD%s to download, %ss%s to save, or %sp%s to print:"
62 ", %sm%s to mail, %sD%s to download:"
63 ", <m> to mail, <D> to download:"
64 ",\n   <m> to mail, <D> to download, <s> to save, or <p> to print:"
65 "Address syntax rejected..."
66 "Bold Search words in Builtin Pager"
67 "Bookmarks"
68 "Can't open old file.."
69 "Can't write to SYS$SCRATCH!"
70 "Can't write to the /tmp directory!"
71 "Cannot Open requested file.."
72 "Cannot connect to host %.40s, port %d."
73 "Choose a document type"
74 "Choose a download method"
75 "Connect to a new Gopher Server"
76 "Connect to an anonymous FTP Server via the Gopher gateway"
77 "Connecting..."
78 "Connection failed: %s."
79 "Connection to remote host failed."
80 "Couldn't create '%s'"
81 "Couldn't execute %s"
82 "Couldn't find text"
83 "Couldn't make a tmp file!\n"
84 "Encountered printing problem, sorry..."
85 "Error invoking callable TPU as a pager!!!"
86 "Exit: u"
87 "Fetching Fields..."
88 "File didn't transfer successfully"
89 "Gopher Directory Information"
90 "Gopher Error"
91 "Gopher File"
92 "Gopher Help File"
93 "Gopher Item Information"
94 "Gopher Options"
95 "Gopher Transmission Error"
96 "Help: ?"
97 "Home Gopher server: %.59s"
98 "Host to query:"
99 "Hostname"
100 "Hostname is unknown."
101 "I don't understand your terminal type\n"
102 "Internet Gopher Information Client v%s.%s.%d"
103 "Link Info"
104 "Local Date and Time"
105 "Mail current document to:"
106 "Mailing File..."
107 "Mailing file to %s..."
108 "Movie viewing not yet implemented"
109 "Name for this bookmark:"
110 "Network Error"
111 "No"
112 "No bookmarks are defined"
113 "No display command is mapped to this view!"
114 "No such user '%s'"
115 "PageDown: <SPACE>"
116 "PageDown: Space"
117 "PageUp: b"
118 "Port"
119 "Press "
120 "Press <RETURN> to continue"
121 "Press <RETURN> when you're ready\n"
122 "Print current document"
123 "Problems Writing"
124 "Really quit (y/n) ?"
125 "Receiving Directory..."
126 "Receiving File..."
127 "Receiving HTML page..."
128 "Receiving Information..."
129 "Receiving MIME File..."
130 "Receiving Movie..."
131 "Receiving Sound..."
132 "Receiving Image..."
133 "Retrieving Directory..."
134 "Return to Menu: u"
135 "Root menu: "
136 "Save in file:"
137 "Save list of items in file:"
138 "Saving File..."
139 "Search directory titles for:"
140 "Search failed..."
141 "Search text for:"
142 "Searching Text..."
143 "Searching..."
144 "Selector (Optional)"
145 "Show host's local date and time"
146 "Size       Language      Document Type\n"
147 "---------- ------------- ----------------------------\n"
148 "Sorry, cannot display this file"
149 "Sorry, can't delete top level directory."
150 "Sorry, can't download that!"
151 "Sorry, can't make a bookmark of bookmarks"
152 "Sorry, can't save files with this account"
153 "Sorry, can't spawn in with this account"
154 "Sorry, can't save that item to a file!"
155 "Sorry, cannot print this document"
156 "Sorry, no method to print this document"
157 "Sorry, telnet is not available."
158 "Sorry, this machine doesn't support images"
159 "Sorry, this machine doesn't support sounds"
160 "Sorry, tn3270 is not available."
161 "Sorry, you are not allowed to print files"
162 "Sorry, you are not allowed to save files"
163 "Sorry, you are not allowed to set options in secure mode."
164 "Sorry, you're not allowed to do this"
165 "Sorry, this machine doesn't support movies"
166 "Sorry, no viewer for the file...."
167 "Spawn to DCL failed!"
168 "Spawn to default shell failed!"
169 "Spawning DCL subprocess.  Logout to return to Gopher.\n"
170 "Spawning your default shell.  Type 'exit' to return to Gopher.\n\n"
171 "Start your capture now...\n\n"
172 "Start your download now...\n"
173 "System problem, unable to mail"
174 "The filename is:"
175 "Unable to allocate a socket."
176 "Unix piping requested.  Check your configuration!"
177 "Unknown error."
178 "Use '/' to define a search first..."
179 "View item number: "
180 "Yes"
181 "Your Choice"
182 "\nDownload Complete. %d total bytes, %d bytes/sec\n"
183 "\nDownload could not be completed, sorry... \n"
184 "\nPress %sRETURN%s to continue"
185 "\nPress <RETURN> to continue"
186 "\n\nServer Information\n"
187 "anonymous FTP Host"
188 "gopher: Nothing received for main menu, can't continue\n"
189 "The 'd'elete command is only for bookmarks."
190 "^G      : Cancel"
191 "OK: Enter"
192 "Tab, ^N : Move to next field"
193 "^P      : Move to previous field"
194 "^F      : Display next page"
195 "^B      : Display previous page"
196 "^-      : Help (^/ or ^7 may work)"
197 "Enter   : Accept"
198 "[Help: ^-]  [Cancel: ^G]"
199 "[Cycle Values: Space]  [List Values: l]"
200 "Select an item"
$
$ Choose menu..
$
201 "Form Help"
202 "^G        : Cancel"
203 "Down, ^N  : Move to next choice"
204 "Up, ^P    : Move to previous choice"
205 "Space, ^F : Display next page"
206 "b, ^B     : Display previous page"
207 "^         : Display first page"
208 "$         : Display last page"
209 "0-9       : Select a specific choice"
210 "Enter     : Select current choice"
211 "Cancel: ^G"
212 " (default)"
213 "Choice Dialog Help"
214 "Nothing available."
215 "Warning, bad line in gopherrc: %s\n"
216 "Aborting gopher configuration save!!"
217 "Text"
218 "A new configuration is available.  Load it?"
219 "Default System Printer"
220 "ANSI attached Printer"
221 "Print to"

$ Default language/region gopher+ view to choose

222 "En_US"
$
$  Multilingual HELP files are now possible
$                      If CONF.H defines GOPHERHELP_SECURE, make sure you
$                      have a separate file for secure users' help that
$                      doesn't document features they're not allowed to use.
$  For VMS:
$
223 "GopherP_Dir:gopher.hlp"
224 "GopherP_Dir:gopher.hlp_secure"
$
$  For Unix:
$
225 "/usr/local/lib/gopher.hlp"
226 "/usr/local/lib/gopher.hlp_secure"
$
$ Gripe Enhancements
$
227 "Sorry, can't submit gripes in secure mode"
228 "Cannot send mail to null address..."
229 "Regarding the following Gopher item:\n"
230 "To"
231 "<Last Line>"

$
$ A message that asks the User if they speak this language..
$
232 "Do you speak English?"

233 " Downloading %d bytes"
234 "    1200bps: %d minutes\n"
235 "    2400bps: %d minutes\n"
236 "   14400bps: %d minutes\n\n"

$
$ Add to post-pager option list in SecureMode and NoShellMode
$
237 ", %sD%s to download:"
238 ", <D> to download:"

