
$quote "


$ Translated by Mark E. Shoulson (shoulson@cs.columbia.edu).
$ Welcome message...
$

1 "<Gopher> qo' Da'elpu'.  maj.  nuqneH?\n\n"
2 "<Gopher> lo'lu' net vuS, 'ej Qap 'e' lay' pagh.\n"
3 "jabbI'ID <Copyright>'e' ngaSbogh De'ghom yIlaD.\n\n"
4 ""

5 "Copyright 1991-2000 by the Regents of the University of Minnesota\n\n"
6 "<Internet> <Gopher> De' SuqwI' %s.%s tI'ta'ghach %d (%s).\n"
7 "ruchmeH, <RETURN> yI'uy.\n"

$
$ Errors in .gopherrc
$
8 "<gopher> QapbeHmeH De' vIqonlaHbe'!!"

$
$ Help for command line
$

9 "lo'meH: %s [-sSbDr] [-T Segh] [-p He] [-t pong] [De' nobwI' pong] [De'wI' lojmItHey]\n"
10 "     -s      Hung mIw, patlh ghajbe'bogh lo'wI'\n"
11 "     -S      Hung mIw, patlh ghajbogh lo'wI'\n"
12 "     -p He   jabbI'ID wa'DIch SuqmeH Hevam ghoSlu'nIS\n"
13 "     -T Segh jabbI'ID wa'DIch Segh\n"
14 "     -i      nejmeH De'Hom (-T 7-vaD)\n"
15 "     -b      Daqtamey wa'DIch\n"
16 "     -r      lo'wI' Hop\n"
17 "     -D      lughmoHmeH mIw\n"

$
$ Pager help..
$

18 "De' HotlhwI' QaHbogh De'"
19 "u, ^G, poS     : HIDjolevDaq yIchegh"
20 "Daq chIm, bIng : tlha'bogh De'jIH yIHotlh"
21 "b, Dung        : nungbogh De'jIH yIHotlh"
22 "/              : mu'Hey yInej"
23 "m              : jabbI'IDvam yIlab"
24 "s              : jabbI'IDvam yIqon"
25 "p              : navDaq jabbI'IDvam yIghItlh"
26 "D              : jabbI'IDvam yISuq"

$
$ New Application Menu
$
27 "De' Segh"
28 "HotlhmeH ghunlu'bogh mIw"
29 "ghItlhmeH ghunlu'bogh mIw"

$
$ Top Level Options
$
30 "DuHmey motlh"
31 "HotlhmeH DuHmey choH"
32 "ghItlhmeH ghunlu'bogh mIw DuHmey choH"
33 "De' Segh chu' ngu'"

$
$ Telnet connection
$
34 "yIghuH!!! tugh <Internet> <Gopher> qo' Damej"
35 "'ej De'wI' latlh DaQumchoH."
36 "Qumbe'chuqchoHchugh De'wI', <control> Da'uytaHvIS"
37 "] yI'uy, 'ej <quit> yIghItlh"
38 "^ yI'uy, 'ej <q> yIghItlh."
39 "%.40s lojmItHey %d vIQummeH, %s vIlo'."
40 "%.40s vIQummeH, %s vIlo'."
41 "mungu'meH De'wI' Hop, pongvaD \"%.40s\" vInob."
$
$ HTML menu
$
42 "yIghuH!!! tugh <Internet> <Gopher> qo' Damej"
43 "'ej HTML HotlhwI' DaQumchoH.  HotlhwI' QaH 
44 "jabbI'ID yIlaD, lo'meH mIwDaj DaSovchu'be'chugh."
45 "HotlhwI' DamejDI', SIbI'"
46 "<Gopher> SuqwI'Daq DacheghmoHlu'."
$
$ Other html msgs
$
47 "HTML yajbe' De'wI'vam.  Do'Ha'."

$
$ gopher.c
$
48 "De'vam loHwI' vItu'laHbe'.  Do'Ha'."

$
$ Gripe form msgs
$
49 "jabbI'IDlIj DalabmeH, <Enter> yI'uy."
50 "jIH HeH DacholDI', bIghItlhtaHvIS, <tab> yI'uy."
51 "qech"
52 "qay' Dochvam"
53 "jabbI'ID vIlablaHbe'..."
54 "bIbep %s-vaD 'e' vIja'..."
55 "mu'meyvam yInej:"
56 "  HaSta De' mI': %d/%d"
57 " DaQaHlu'meH, "
58 " bImevmeH"
59 " HIDjolev bIngDaq bIghoSmeH"
60 "%s: HIDjolev wa'DIch vIHevbe'.  vItaHlaHbe'."
61 "jabbI'ID DalabmeH: %sm%s, De' DaSuqmeH: %sD%s, De' DachoqmeH: %ss%s, pagh De' ghItlhlu' 'e' DaqaSmoHmeH: %sp%s."
62 ", jabbI'ID DalabmeH: %sm%s, De' DaSuqmeH: %sD%s"
63 ", jabbI'ID DalabmeH: <m>, De' DaSuqmeH: <D>."
64 ",\n   jabbI'ID DalabmeH: <m>, De' DaSuqmeH: <D>, bIchoqmeH: <s>, pagh De' ghItlhlu' 'e' DaqaSmoHmeH: <p>."
65 "Daq De' lajlu'."
66 "SuqwI' De' HotlhwI'Daq jaqlaw' mu'mey lunejlu'bogh"
67 "Daqtamey"
68 "De' ngo' vInaw'laHbe'"
69 "SYS$SCRATCH vIghItlhlaHbe'!"
70 "/tmp De'DaqDaq jIghItlhlaHbe'!"
71 "De' Datlhobpu'bogh vInaw'laHbe'.."
72 "%.40s De'wI', lojmItHey %d vInaw'laHbe'."
73 "De' Segh yIwIv"
74 "De' SuqmeH mIw yIwIv"
75 "<Gopher> ma'wI' chu' yInaw'"
76 "<FTP> ma'wI' Danaw'meH (pagh pong DanoblaH), <Gopher> mIw yIlo'"
77 "naw'choHlI'..."
78 "jInaw' 'e' vInIDDI', jIluj: %s."
79 "De'wI' Hop vInaw'laHbe'."
80 "'%s' vIcherlaHbe'."
81 "'%s' vIpablaHbe'."
82 "mu'mey vItu'laHbe'."
83 "De' ru' vIchenmoHlaHbe'!\n"
84 "jIghItlh 'e' vInIDDI', qay'lu'.  Do'Ha'..."
85 "De' HotlhmeH <TPU> vIlo' 'e' vInIDDI', Qaghbej vay'!!!"
86 "mej: u"
87 "yotlhHey SuqlI'..."
88 "De' jIQay 'e' vInIDDI', jIQapbe'"
89 "<Gopher> De'ghom De'"
90 "<Gopher> Qagh"
91 "<Gopher> De'"
92 "<Gopher> QaH De'"
93 "<Gopher> De' De'"
94 "<Gopher> DuHmey"
95 "<Gopher> labmeH Qagh"
96 "QaH: ?"
97 "juH <Gopher> ma'wI': %.59s"
98 "De'wI' jIyu'nISbogh:"
99 "De'wI' pong"
100 "De'wI' pong jISovbe'."
101 "SeHlawlIj SeghHey vIyajbe'\n"
102 "<Internet> <Gopher> De' SuqwI' v%s.%s.%d"
103 "rarwI' De'"
104 "DaqlIj jaj mI' poH De' je"
105 "HevwI'vamvaD De''e' DaH Hotlhlu'bogh yIlI':"
106 "De' vIlI'lI'..."
107 "%s-vaD De' vIlI'lI'..."
108 "wej vIHtaHbogh rurwI' vIcha'laH"
109 "Daqtavam pong:"
110 "jatlhchuqDI' De'wI' Qagh"
111 "ghobe'"
112 "pagh Daqtamey lucherlu'pu'"
113 "ghu'vamvaD jIcha'meH vIra'lu'pu' pagh!"
114 "lo'wI' <%s> tu'be'lu'"
115 "tlha'bogh HaSta De': <Daq chIm>"
116 "tlha'bogh HaSta De': Daq chIm"
117 "nungbogh HaSta De': b"
118 "lojmItHey"
119 "Dochvam yI'uy: "
120 "bItaHmeH, <RETURN> yI'uy"
121 "bItaHrupDI', <RETURN> yI'uy\n"
122 "De''e' DaH Holthlu'bogh yIghItlh"
123 "jIghItlhDI' qay'lu'"
124 "bIbup DaneHbej'a' (y/n) ?"
125 "De'ghom HevlI'..."
126 "De' HevlI'..."
127 "<HTML> De' HevlI'..."
128 "De' HevlI'..."
129 "<MIME> De' HevlI'..."
130 "vIHbogh rurwI' HevlI'..."
131 "chuSmeH De' HevlI'..."
132 "rurwI' HevlI'..."
133 "HIDjolev SuqlI'..."
134 "HIDjolevDaq yIchegh: u"
135 "HIDjolev wa'DIch: "
136 "De' vIchoqbogh pong:"
137 "HIDjolev vIchoqbogh pong:"
138 "De' choqlI'..."
139 "HIDjolevDaq Dochvam yInej:"
140 "jInejta' 'ach jIluj..."
141 "ghItlhDaq Dochvam yInej:"
142 "ghItlhDaq nejlI'..."
143 "nejlI'..."
144 "wIvwI' (DuH)"
145 "ma'wI' Daq jaj mI' poH De' je yIcha'"
146 "tIntaHghaH       Hol          ghItlh Segh\n"
147 "---------- ------------- ----------------------------\n"
148 "De'vam vIcha'laHbe'.  Do'Ha."
149 "De' HIDjolev wa'DIch vIQaw'laHbe'.  Do'Ha'."
150 "Dochvetlh vISuqlaHbe'!  Do'Ha'."
151 "Daqtamey Daqta vIcherlaHbe'.  Do'Ha'."
152 "De' choqlaHbe' Hung ghotHeyvam.  Do'Ha'."
153 "De'wI' Qu' cherlaHbe' Hung ghotHeyvam.  Do'Ha'."
154 "Dochvetlh De' vIchoqlaHbe'!  Do'Ha'."
155 "ghItlhvam vIghItlhlaHbe'.  Do'Ha'."
156 "ghItlhvam vIghItlhmeH mIw tu'be'lu'.  Do'Ha'."
157 "<telnet> Dalo'laHbe'.  Do'Ha'."
158 "rurwI' cha'laHbe' De'wI'vam.  Do'Ha'."
159 "chuSlaHbe' De'wI'vam.  Do'Ha'."
160 "<tn3270> Dalo'laHbe'.  Do'Ha'."
161 "De' DaghItlh net tuch.  Do'Ha'."
162 "De' Dachoq net tuch.  Do'Ha'."
163 "Hung mIw vIlo'taHvIS wIvmey DawIv net tuch.  Do'Ha'."
164 "ta'vam Data' net tuch.  Do'Ha'."
165 "vIHbogh rurwI' cha'laHbe' De'wI'vam.  Do'Ha'."
166 "De'vamvaD cha'wI' tu'be'lu'.  Do'Ha'."
167 "<DCL> De'wI' Qu' vIcher 'e' vInIDDI' jIluj!"
168 "qalobmeH mIwlIj motlh vIcherlaHbe'!"
169 "<DCL> De'wI' Qu' vIcherlI'.  <Gopher>Daq bIcheghmeH, yIrarHa'.\n"
170 "qalobmeH De'wI' mIwlIj motlh vIcherlI'.  <Gopher>Daq bIcheghmeH, 'exit' yIghItlh.\n\n"
171 "DaH yIqonchoH...\n\n"
172 "DaH HevchoH De'wI'lIj...\n"
173 "qay' pat.  jabbI'ID vIlablaHbe'"
174 "De' pong:"
175 "De'He vItu'laHbe'."
176 "De' QaymeH <UNIX> mIw tlhoblu'.  QapbeHchu''a' De'wI'?"
177 "qay' vay' Sovbe'lu'bogh."
178 "bIruchpa', bInejmeH '/' Dalo'nIS..."
179 "Doch vIlegh vIneHbogh mI': "
180 "HISlaH"
181 "wIvlIj"
182 "\nDe' lI'lu'chu'ta'.  %d vIHevpu' (qaStaHvIS wa' lup %d vIHev)\n"
183 "\nDe' lI'laHbe'law' lI'wI'.  Do'Ha'.\n"
184 "\nruchmeH, %sRETURN%s yI'uy"
185 "\nruchmeH, <RETURN> yI'uy"
186 "\n\nma'wI' De'\n"
187 "pong poQbe'bogh <FTP> ma'wI'"
188 "gopher: HIDjolev wa'DIchvaD pagh vIHevpu'.  jItaHlaHbe'.\n"
189 "Daqta neH DaQaw'laH ('d')."
190 "^G      : yIqIl"
191 "lu': <Enter>"
192 "Tab, ^N : tlha'bogh yotlhHey yIghoS"
193 "^P      : nungbogh yotlhHey yIghoS"
194 "^F      : tlha'bogh De'jIH yIHotlh"
195 "^B      : nungbogh De'jIH yIHotlh"
196 "^-      : HIQaH! (chaq Qap je ^/ ^7 joq)"
197 "Enter   : yIlaj"
198 "[QaH: ^-]  [qIl: ^G]"
199 "[DuHmey yIchoH: Daq chIm]  [DuHmey yIcha': l]"
200 "Doch yIwIv"
$
$ Choose menu..
$
201 "wIvmeH QaH"
202 "^G           : yIqIl"
203 "bIng, ^N     : tlha'bogh DuHDaq yIghoS"
204 "Dung, ^P     : nungbogh DuHDaq yIghoS"
205 "Daq chIm, ^F : tlha'bogh De'jIH yIHotlh"
206 "b, ^B        : nungbogh De'jIH yIHotlh"
207 "^            : De'jIH wa'DIch yIHotlh"
208 "$            : De'jIH Qav yIHotlh"
209 "0-9          : wa' DuH yIwIv"
210 "Enter        : DuHvam yIwIv"
211 "yIqIl: ^G"
212 " (motlh)"
213 "wIvDI' QummeH QaH"
214 "pagh vISuqlaH."
215 "yIghuH: <gopherrc>Daq mu'tlhegh vIyajbe'bogh tu'lu': %s\n"
216 "<gopher> QapbeHmeH De' vItoDbe'Aborting gopher configuration save!!"
217 "pIqaD"
218 "QapbeHmeH De' chu' tu'lu'.  'oH vIlo'nIS'a'?"
219 "De'wI' ghItlhwI' motlh"
220 "<ANSI> ghItlhwI'"
221 "ghItlhmeH ghItlhwI'vam yIlo':"
$
$ Default language/region gopher+ view to choose
$
222 "Klingon"
$
$  Multilingual HELP files are now possible
$			If CONF.H defines GOPHERHELP_SECURE, make sure you
$			have a separate file for secure users' help that
$			doesn't document features they're not allowed to use.
$  For VMS:
$
223 "GopherP_Dir:gopher.hlp"
224 "GopherP_Dir:gopher.hlp_secure"
$
$  For Unix:
$
225 "/usr/local/lib/gopher.hlp"
226 "/usr/local/lib/gopher.hlp_secure"
$
$ Gripe Enhancements
$
227 "bIbeplaHbe' Hung mIw Dalo'taHvIS.  Do'Ha'."
228 "jabbI'ID vIlabmeH Daq De' tu'be'lu'!  jabbI'ID vIlablaHbe'..."
229 "tlha'bogh <Gopher> De' vIbuS:\n"
230 "ghotvamvaD:"
231 "<mu'tlhegh Qav>"

$
$ A message that asks the User if they speak this language..
$
232 "tlhIngan Hol wIjatlh."

233 " De' HevlI': %d"
234 "    1200bps: %d tup\n"
235 "    2400bps: %d tup\n"
236 "   14400bps: %d tup\n\n"

$
$ Add to post-pager option list in SecureMode and NoShellMode
$
237 ", De' DaHevmeH %sD%s:"
238 ", De' DaHevmeH <D>:"

$
$ Sorry, only this language is available
$	-- msg # overlap in v2.13 !!!
$221 "tlhIngan Hol neH vIjatlhlaH.  Do'Ha'."
