
$quote "


$ Translation courtesy of Tona Henderson <TAH@psulias.psu.edu>
$ Welcome message...
$

1 "elcome-Way o-tay e-thay onderful-way orld-way of-ay opher-Gay!\n\n"
2 "opher-Gay as-hay imitations-lay on-ay its-ay use-ay and-ay omes-cay ithout-way\n"
3 "a arranty-way.  ease-play efer-ray o-tay e-thay ile-fay 'opyright-cay' included\n"
4 "in-ay e-thay istribution-day.\n\n"

5 "opyright-Cay 1991-2000 y-bay e-thay egents-Ray of-ay e-thay University-ay of-ay innesota-May\n\n"
6 "Internet-ay opher-Gay Information-ay ient-Clay %s.%s patch%d (%s)\n"
7 "ess-Pray ETURN-RAY o-tay ontinue-cay\n"

$ 
$ Errors in .gopherrc
$
8 "an't-cay ite-wray o-tay opher-gay onfiguration-cay ile-fay!!"

$
$ Help for command line 
$

9 "Usage-ay: %s [-sSbDr] [-T ype-tay] [-p ath-pay] [-t itle-tay] [ostname-hay ort-pay]+\n"
10 "     -s      ecure-say ode-may, users-ay ithout-way own-ay account-ay\n"
11 "     -S      ecure-say ode-may, users-ay ith-way own-ay account-ay\n"
12 "     -p path ecify-spay ath-pay o-tay initial-ay item-ay\n"
13 "     -T type ype-Tay of-ay initial-ay item-ay\n"
14 "     -i      earch-Say argument-ay (for -T 7)\n"
15 "     -b      ookmarks-Bay irst-fay\n"
16 "     -r      emote-Ray user-ay\n"
17 "     -D      ebug-Day ode-may\n"

$
$ Pager help..
$

18 "ager-Pay elp-Hay"
19 "u, ^G, left : eturn-Ray o-tay enu-may"
20 "space, down : ove-May o-tay e-thay ext-nay age-pay"
21 "b, up       : ove-May o-tay e-thay evious-pray age-pay"
22 "/           : earch-Say or-fay ext-tay"
23 "m           : ail-may urrent-cay ocument-day"
24 "s           : ave-say urrent-cay ocument-day"
25 "p           : int-pray urrent-cay ocument-day"
26 "D           : ownload-day urrent-cay ocument-day"

$ 
$ New Application Menu
$ 
27 "ontent-Cay ype-Tay ame-Nay"
28 "isplay-Day Application-Ay"
29 "inting-Pray Application-Ay"

$ 
$ Top Level Options
$ 
30 "eneral-Gay Options-Ay"
31 "onfigure-Cay isplay-Day Applications-Ay"
32 "onfigure-Cay inting-Pray Applications-Ay"
33 "efine-Day ew-Nay ontent-Cay ype-Tay"

$
$ Telnet connection
$
34 "arning-Way!!!!!, ou-Yay are-ay about-ay o-tay eave-lay e-thay Internet-ay"
35 "opher-Gay ogram-pray and-ay onnect-cay o-tay another-ay ost-hay. If-ay"
36 "ou-yay et-gay uck-stay ess-pray e-thay ontrol-cay ey-kay and-ay e-thay"
37 "] ey-kay, and-ay en-thay ype-tay it-quay"
38 "^ ey-kay, and-ay en-thay ype-tay q."
39 "onnecting-cay o-tay %.40s, ort-pay %d using-ay %s."
40 "onnecting-cay o-tay %.40s using-ay %s."
41 "Use-ay e-thay account-ay ame-nay \"%.40s\" o-tay og-lay in-ay"
$
$ HTML menu
$
42 "arning-Way!!!!!, ou-yay are-ay about-ay o-tay eave-lay e-thay Internet-ay opher-Gay"
43 "ient-Clay and-ay onnect-cay o-tay an-ay HTML owser-Bray.  Use-ay e-thay owser-Bray"
44 "elp-Hay if-ay ou-yay are-ay ot-nay amiliar-fay ith-way its-ay ommands-cay."
45 "Upon-ay itting-quay om-fray e-thay owser-Bray, ou-yay ill-way e-bay eturned-ray o-tay"
46 "e-thay Internet-ay opher-Gay ient-Clay."
$
$ Other html msgs
$
47 "orry-Say, is-thay ient-clay oes-day ot-nay upport-say HTML"

$
$ gopher.c
$
48 "an't-cay ind-fay an-ay administrator-ay or-fay is-thay item-ay, orry-say!"

$ 
$ Gripe form msgs
$ 
49 "it-Hay e-thay Enter-ay ey-kay o-tay end-say our-yay essage-may."
50 "it-Hay e-thay ab-Tay ey-kay at-ay e-thay end-ay of-ay each-ay ine-lay ou-yay ype-tay."
51 "ubject-Say"
52 "oblem-Pray"
53 "annot-Cay end-say ail-may..."
54 "ailing-may ipe-gray o-tay %s..."
55 "ords-Way o-tay earch-say or-fay"
56 " age-Pay: %d/%d"
57 " or-fay elp-Hay, "
58 " o-tay uit-Qay"
59 " o-tay o-gay up-ay a enu-may"
60 "%s: othing-Nay eceived-ray or-fay ain-may enu-may, an't-cay ontinue-cay\n"
61 "%sm%s o-tay ail-may, %sD%s o-tay ownload-day, %ss%s o-tay ave-say, or %sp%s o-tay int-pray:"
62 ", %sm%s o-tay mail, %sD%s o-tay ownload-day:"
63 ", <m> o-tay ail-may, <D> o-tay ownload-day:"
64 ",\n   <m> o-tay ail-may, <D> o-tay ownload-day, <s> o-tay ave-say, or <p> o-tay int-pray:"
65 "Address-ay yntax-say ejected-ray..."
66 "old-Bay earch-Say ords-way in-ay uiltin-Bay ager-Pay"
67 "ookmarks-Bay"
68 "an't-Cay open-ay old-ay ile-fay.."
69 "an't-Cay ite-wray o-tay SYS$SCRATCH!"
70 "an't-Cay ite-wray o-tay e-thay /tmp irectory-day!"
71 "annot-Cay Open-ay equested-ray ile-fay.."
72 "annot-Cay onnect-cay o-tay ost-hay %.40s, ort-pay %d."
73 "oose-Chay a ocument-day ype-tay"
74 "oose-Chay a ownload-day ethod-may"
75 "onnect-Cay o-tay a ew-nay opher-Gay erver-Say"
76 "onnect-Cay o-tay an anonymous-ay TP-Fay erver-Say ia-vay e-tahy opher-Gay ateway-gay"
77 "onnecting-Cay..."
78 "onnection-Cay ailed-fay: %s."
79 "onnection-Cay o-tay emote-ray ost-hay ailed-fay."
80 "ouldn't-Cay eate-cray '%s'"
81 "ouldn't-Cay execute-ay %s"
82 "ouldn't-Cay ind-fay ext-tay"
83 "ouldn't-Cay ake-may a tmp ile-fay!\n"
84 "Encountered-ay inting-pray oblem-pray, orry-say..."
85 "Error-ay invoking-ay allable-cay TPU as-ay a ager-pay!!!"
86 "Exit-ay: u"
87 "etching-Fay ields-Fay..."
88 "ile-Fay idn't-day ansfer-tray uccessfully-say"
89 "opher-Gay irectory-Day Information-ay"
90 "opher-Gay Error-ay"
91 "opher-Gay ile-Fay"
92 "opher-Gay elp-Hay ile-Fay"
93 "opher-Gay Item-ay Information-ay"
94 "opher-Gay Options-ay"
95 "opher-Gay ansmission-Tray Error-ay"
96 "elp-Hay: ?"
97 "ome-Hay opher-Gay erver-say: %.59s"
98 "ost-Hay o-tay uery-qay:"
99 "ostname-Hay"
100 "ostname-Hay is-ay unknown-ay."
101 "I on't-day understand-ay our-yay erminal-tay ype-tay\n"
102 "Internet-ay opher-Gay Information-ay ient-Clay v%s.%s.%d"
103 "ink-Lay Info-ay"
104 "ocal-Lay ate-Day and-ay ime-Tay"
105 "ail-May urrent-cay ocument-day o-tay:"
106 "ailing-May ile-Fay..."
107 "ailing-May ile-fay o-tay %s..."
108 "ovie-May iewing-vay ot-nay et-yay implemented-ay"
109 "ame-Nay or-fay is-thay ookmark-bay:"
110 "etwork-Nay Error-ay"
111 "o-Nay"
112 "o-Nay ookmarks-bay are-ay efined-day"
113 "o-Nay isplay-day ommand-cay is-ay apped-may o-tay is-thay iew-vay!"
114 "o-Nay uch-say user-ay '%s'"
115 "ageDown-Pay: <SPACE>"
116 "ageDown-Pay: Space"
117 "ageUp-Pay: b"
118 "ort-Pay"
119 "ess-Pray "
120 "ess-Pray <RETURN> o-tay ontinue-cay"
121 "ess-Pray <RETURN> en-whay ou're-yay eady-ray\n"
122 "int-Pray urrent-cay ocument-day"
123 "oblems-Pray iting-Wray"
124 "eally-Ray uit-qay (y/n) ?"
125 "eceiving-Ray irectory-Day..."
126 "eceiving-Ray ile-Fay..."
127 "eceiving-Ray HTML age-pay..."
128 "eceiving-Ray Information-ay..."
129 "eceiving-Ray MIME ile-Fay..."
130 "eceiving-Ray ovie-May..."
131 "eceiving-Ray ound-Say..."
132 "eceiving-Ray Image-ay..."
133 "etrieving-Ray irectory-Day..."
134 "eturn-Ray o-tay enu-May: u"
135 "oot-Ray enu-may: "
136 "ave-Say in-ay ile-fay:"
137 "ave-Say ist-lay of-ay items-ay in-ay ile-fay:"
138 "aving-Say ile-Fay..."
139 "earch-Say irectory-day itles-tay or-fay:"
140 "earch-Say ailed-fay..."
141 "earch-Say ext-tay or-fay:"
142 "earching-Say ext-Tay..."
143 "earching-Say..."
144 "elector-Say (Optional-ay)"
145 "ow-Shay ost's-hay ocal-lay ate-day and-ay ime-tay"
146 "ize-Say    anguage-Lay   ocument-Day ype-Tay\n"
147 "---------- ------------- ----------------------------\n"
148 "orry-Say, annot-cay isplay-day is-thay ile-fay"
149 "orry-Say, an't-cay elete-day op-tay evel-lay irectory-day."
150 "orry-Say, an't-cay ownload-day at-thay!"
151 "orry-Say, an't-cay ake-may a ookmark-bay of-ay ookmarks-bay"
152 "orry-Say, an't-cay ave-say iles-fay ith-way is-thay account-ay"
153 "orry-Say, an't-cay awn-spay in-ay ith-ay is-thay account-ay"
154 "orry-Say, an't-cay ave-say at-thay item-ay o-tay a ile-fay!"
155 "orry-Say, annot-cay int-pray is-thay ocument-day"
156 "orry-Say, o-nay ethod-may o-tay int-pray is-thay ocument-day"
157 "orry-Say, elnet-tay is-ay ot-nat available-ay."
158 "orry-Say, is-thay achine-may oesn't-day upport-say images-ay"
159 "orry-Say, is-thay achine-may oesn't-day upport-say ounds-say"
160 "orry-Say, tn3270 is-ay ot-nay available-ay."
161 "orry-Say, ou-yay are-ay ot-nay allowed-ay o-tay int-pray iles-fay"
162 "orry-Say, ou-yay are-ay ot-nay allowed-ay o-tay ave-say iles-fay"
163 "orry-Say, ou-yay are-ay ot-nay allowed-ay o-tay et-say options-ay in-ay ecure-say ode-may."
164 "orry-Say, ou're-yay ot-nay allowed-ay o-tay o-day is-thay"
165 "orry-Say, is-thay achine-may oesn't-day upport-say ovies-may"
166 "orry-Say, o-nay iewer-vay or-fay e-thay ile-fay...."
167 "awn-Spay o-tay DCL ailed-fay!"
168 "awn-Spay o-tay efault-day ell-shay ailed-fay!"
169 "awning-Spay DCL ubprocess-say.  ogout-Lay o-tay eturn-ray o-tay opher-Gay.\n"
170 "awning-Spay our-yay efault-day ell-shay.  ype-Tay 'exit' o-tay eturn-ray o-tay opher-Gay.\n\n"
171 "art-Stay our-yay apture-cay ow-nay...\n\n"
172 "art-Stay our-yay ownload-day ow-nay...\n"
173 "ystem-Say oblem-pray, unable-ay o-tay ail-may"
174 "e-Thay ilename-fay is-ay:"
175 "Unable-ay o-tay allocate-ay a ocket-say."
176 "Unix-ay iping-pay equested-ray.  eck-Chay our-yay onfiguration-cay!"
177 "Unknown-ay error-ay."
178 "Use-ay '/' o-tay efine-day a earch-say irst-fay..."
179 "iew-Vay item-ay umber-nay: "
180 "es-Yay"
181 "our-Yay oice-Chay"
182 "\nownload-Day omplete-Cay. %d otal-tay ytes-bay, %d ytes-bay/ec-say\n"
183 "\nownload-Day ould-cay ot-nay e-bay ompleted-cay, orry-say... \n"
184 "\ness-Pray %sRETURN%s o-tay ontinue-cay"
185 "\ness-Pray <RETURN> o-tay ontinue-cay"
186 "\n\nerver-Say Information-ay\n"
187 "anonymous-ay FTP ost-Hay"
188 "opher-gay: othing-Nay eceived-ray or-fay ain-may enu-may, an't-cay ontinue-Cay\n"
189 "e-Thay 'd'elete ommand-cay is-ay only-ay or-fay ookmarks-bay."
190 "^G      : ancel-Cay"
191 "OK: Enter-ay"
192 "Tab, ^N : ove-May o-tay ext-nay ield-fay"
193 "^P      : ove-May o-tay evious-pray ield-fay"
194 "^F      : isplay-Day ext-nay age-pay"
195 "^B      : isplay-Day evious-pray age-pay"
196 "^-      : elp-Hay (^/ or ^7 ay-may ork-way)"
197 "Enter-ay: Accept-ay"
198 "[elp-Hay: ^-]  [ancel-Cay: ^G]"
199 "[ycle-Cay alues-Vay: Space]  [ist-Lay alues-Vay: l]"
200 "elect-Say an-ay item-ay"
$
$ Choose menu..
$
201 "orm-Fay elp-Hay"
202 "^G        : ancel-Cay"
203 "Down, ^N  : ove-May o-tay ext-nay oice-chay"
204 "Up, ^P    : ove-May o-tay evious-pray oice-chay"
205 "Space, ^F : isplay-Day ext-nay age-pay"
206 "b, ^B     : isplay-Day evious-pray age-pay"
207 "^         : isplay-Day irst-fay age-pay"
208 "$         : isplay-Day ast-lay age-pay"
209 "0-9       : elect-Say a ecific-spay oice-chay"
210 "Enter     : elect-Say urrent-cay oice-chay"
211 "ancel-Cay: ^G"
212 " (efault-day)"
213 "oice-Chay ialog-Day elp-Hay"
214 "othing-Nay available-ay."
215 "arning-Way, ad-bay ine-lay in-ay gopherrc: %s\n"
216 "Aborting-ay opher-gay onfiguration-cay ave-say!!"
217 "ext-Tay"
218 "A new configuration is available.  Load it?"
219 "Default System Printer"
220 "ANSI attached Printer"
221 "Print to"

$ Default language/region gopher+ view to choose
222 "En_iglatinpay"
$
$  Multilingual HELP files are now possible
$			If CONF.H defines GOPHERHELP_SECURE, make sure you
$			have a separate file for secure users' help that 
$			doesn't document features they're not allowed to use.
$  For VMS:
$
223 "GopherP_Dir:gopher.hlp"
224 "GopherP_Dir:gopher.hlp_secure"
$
$  For Unix:
$
225 "/usr/local/lib/gopher.hlp"
226 "/usr/local/lib/gopher.hlp_secure"

$
$ Gripe Enhancements
$
227 "orry-Say, an't-cay ubmit-say ipes-gray in-ay ecure-say ode-may"
228 "annot-Cay end-say ail-may o-tay ull-nay address-ay..."
229 "egarding-Ray e-thay ollowing-fay opher-Gay item-ay:\n"
230 "o-Tay"
231 "<ast-Lay ine-Lay>"

$
$ A message that asks the User if they speak this language..
$
232 "all-Shay e-way eak-spay ig-Pay atin-Lay?"

233 " ownloading-Day %d ytes-bay"
234 "    1200bps: %d inutes-may\n"
235 "    2400bps: %d inutes-may\n"
236 "   14400bps: %d inutes-may\n\n"

$
$ Add to post-pager option list in SecureMode and NoShellMode
$
237 ", %sD%s o-tay ownload-day:"
238 ", <D> o-tay ownload-day:"

$
$ Sorry, only this language is available
$	-- msg # overlap in v2.13 !!!
$221 "orry-Say, only-ay ig-Pay atin-Lay is-ay available-ay"

